//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public long ID { get; set; }
        public Nullable<bool> Liked { get; set; }
        public Nullable<bool> Disliked { get; set; }
        public long UserID { get; set; }
        public long ItemID { get; set; }
        public byte ItemLevel { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
