//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public Story()
        {
            this.Comments = new HashSet<Comment>();
            this.StoryDatas = new HashSet<StoryData>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string Descripition { get; set; }
        public int CategoryID { get; set; }
        public long UserID { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public int ViewsCount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<StoryData> StoryDatas { get; set; }
    }
}
