//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NT.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryData
    {
        public long ID { get; set; }
        public long StoryID { get; set; }
        public byte Type { get; set; }
        public string Url { get; set; }
        public string ThumbnailUrl { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Story Story { get; set; }
    }
}
